# Generated by Django 4.1.7 on 2023-03-08 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Book title"
                    ),
                ),
                ("author", models.CharField(max_length=50, verbose_name="Author")),
                (
                    "cover",
                    models.CharField(
                        choices=[("Hard", "Hard"), ("Soft", "Soft")], max_length=50
                    ),
                ),
                (
                    "inventory",
                    models.PositiveIntegerField(verbose_name="Availability of books"),
                ),
                (
                    "daily_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Daily fee",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
