# Generated by Django 4.1.7 on 2023-03-18 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(default=datetime.date(2023, 4, 1)),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
